# Generated by Django 3.2.13 on 2022-06-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20220528_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(
                default='None', upload_to='images', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
