# Generated by Django 3.2.13 on 2022-06-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(
                default='None', max_length=200, verbose_name='id'),
            preserve_default=False,
        ),
    ]
