# Generated by Django 4.0.5 on 2022-06-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_image_options_image_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='place',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
